{% set name = "mkdocs-material" %}
{% set version = "9.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mkdocs_material-{{ version }}.tar.gz
  sha256: da37dba220d9fbfc5f1fc567fafc4028e3c3d7d828f2779ed09ab726ceca77dc


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-requirements-txt
    - hatch-nodejs-version >=0.3.0
    - trove-classifiers >=2023.10.18
  run:
    - python >={{ python_min }}
    - jinja2 >=3.0,<4.dev0
    - markdown >=3.2,<4.dev0
    - mkdocs >=1.6,<2.dev0
    - mkdocs-material-extensions >=1.3,<2.dev0
    - pygments >=2.16,<3.dev0
    - pymdown-extensions >=10.2,<11.dev0
    - babel >=2.10,<3.dev0
    - colorama >=0.4,<1.dev0
    - paginate >=0.5,<1.dev0
    - regex >=2022.4
    - requests >=2.26,<3.dev0

test:
  imports:
    - material
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://squidfunk.github.io/mkdocs-material/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Material Design theme for mkdocs
  doc_url: https://squidfunk.github.io/mkdocs-material/
  dev_url: https://squidfunk.github.io/mkdocs-material/customization/

extra:
  recipe-maintainers:
    - ruben-arts
    - monaldoj
    - marcelotrevisani
    - thewchan
