{% set name = "mkdocs-material" %}
{% set version = "9.5.16" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs_material-{{ version }}.tar.gz
  sha256: 8b89b639592660f24657bb058de4aff0060cd0383148f8f51711201730f17503


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8

    - hatchling
    - hatch-requirements-txt
    - hatch-nodejs-version >=0.3.0
    - trove-classifiers >=2023.10.18
  run:
    - python >=3.8
    - jinja2 ~=3.0
    - markdown ~=3.2
    - mkdocs ~=1.5,>=1.5.3
    - mkdocs-material-extensions ~=1.3
    - pygments ~=2.16
    - pymdown-extensions ~=10.2

    - babel ~=2.10
    - colorama ~=0.4
    - paginate ~=0.5
    - regex >=2022.4
    - requests ~=2.26

test:
  imports:
    - material
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://squidfunk.github.io/mkdocs-material/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Material Design theme for mkdocs
  doc_url: https://squidfunk.github.io/mkdocs-material/
  dev_url: https://squidfunk.github.io/mkdocs-material/customization/

extra:
  recipe-maintainers:
    - ruben-arts
    - monaldoj
    - marcelotrevisani
    - thewchan
