schema_version: 1

context:
  name: mkdocs-material
  version: "9.7.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mkdocs_material-${{ version }}.tar.gz
  sha256: 6776256552290b9b7a7aa002780e25b1e04bc9c3a8516b6b153e82e16b8384bd

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-requirements-txt
    - hatch-nodejs-version >=0.3.0
    - trove-classifiers >=2023.10.18
  run:
    - python >=${{ python_min }}
    - jinja2 >=3.1
    - markdown >=3.2
    - mkdocs >=1.6
    - mkdocs-material-extensions >=1.3
    - pygments >=2.16
    - pymdown-extensions >=10.2
    - babel >=2.10
    - colorama >=0.4
    - paginate >=0.5
    - backrefs >=5.7.post1
    - requests >=2.30

tests:
  - python:
      imports:
        - material
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: A Material Design theme for mkdocs
  homepage: https://squidfunk.github.io/mkdocs-material/
  repository: https://squidfunk.github.io/mkdocs-material/customization/
  documentation: https://squidfunk.github.io/mkdocs-material/

extra:
  recipe-maintainers:
    - ruben-arts
    - monaldoj
    - marcelotrevisani
    - thewchan
