schema_version: 1

context:
  name: mkdocs-material
  version: "9.6.21"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mkdocs_material-${{ version }}.tar.gz
  sha256: b01aa6d2731322438056f360f0e623d3faae981f8f2d8c68b1b973f4f2657870

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-requirements-txt
    - hatch-nodejs-version >=0.3.0
    - trove-classifiers >=2023.10.18
  run:
    - python >=${{ python_min }}
    - jinja2 >=3.0,<4.dev0
    - markdown >=3.2,<4.dev0
    - mkdocs >=1.6,<2.dev0
    - mkdocs-material-extensions >=1.3,<2.dev0
    - pygments >=2.16,<3.dev0
    - pymdown-extensions >=10.2,<11.dev0
    - babel >=2.10,<3.dev0
    - colorama >=0.4,<1.dev0
    - paginate >=0.5,<1.dev0
    - backrefs >=5.7.post1,<6.dev0
    - requests >=2.26,<3.dev0
    # Refer - https://github.com/squidfunk/mkdocs-material/blob/f0b0b5931a386b670c19d3e3b78ecd41da144341/requirements.txt#L36C1-L38C12
    # Temporarily pin click until this is resolved in MkDocs, see
    # https://github.com/mkdocs/mkdocs/issues/4014#issuecomment-3146508306
    - click <8.2.2

tests:
  - python:
      imports:
        - material
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: A Material Design theme for mkdocs
  homepage: https://squidfunk.github.io/mkdocs-material/
  repository: https://squidfunk.github.io/mkdocs-material/customization/
  documentation: https://squidfunk.github.io/mkdocs-material/

extra:
  recipe-maintainers:
    - ruben-arts
    - monaldoj
    - marcelotrevisani
    - thewchan
